### PR TITLE
Fix raw use of TableView, and parameter ordering

### PR DESCRIPTION
**Pull request by dustinkredmond**
There looks to be some raw uses of classes in controlsfx without the proper type parameter. If desired, I will generify the rest of the project as well.

### CODE REVIEW

**Comment by Maxoudela** [comment]
Hi, 

Thanks for the PR. Could you sign our [CLA](http://cla.controlsfx.org/) as specified in our [contributing rules](https://github.com/controlsfx/controlsfx/wiki/Contributing-to-ControlsFX) ?

**Review by Maxoudela — APPROVED** [review]

**Comment by dustinkredmond** [comment]
CLA has been signed

**Comment by abhinayagarwal** [comment]
Please update the year in license header.

> Copyright (c) 2016, 2020, ControlsFX

**Comment by dustinkredmond** [comment]
@abhinayagarwal DIdn't notice that, thanks! License header has been updated.

**Pull request merged**
