### PR TITLE
Upgrade to Java17 and JavaFX17! The test is OK

### PR DESCRIPTION
**Pull request by Yuanuo**
Upgrade to Java17 & JavaFX17!
Just replace the build system from Gradle to Maven!! Maven is really easy!

image

### CODE REVIEW

**Comment by Maxoudela** [comment]
Thanks for the PR but I believe the idea is to fix the gradle build we have. 
I'm unsure that we are willing to move to Maven. 
The diff is outstanding, you must have a config issue that is modifying too much files

**Comment by Yuanuo** [comment]
> Thanks for the PR but I believe the idea is to fix the gradle build we have.
> I'm unsure that we are willing to move to Maven.
> The diff is outstanding, you must have a config issue that is modifying too many files

Although it seems that there are many diffs, the main modification involves 3 parts:
1. Remove all gradle-related configuration files.
2. Several pom.xml has been added.
3. Just rename the fxsampler package name to org.controlsfx.fxsampler. In fact, this step is not necessary, because the package name is not the same. But I just did it.

Upgrade to the new version of JavaFX on the original project (current branch), and there are no compatibility issues caused by syntax and so on. The main problem comes from Gradle and its related plug-ins. For example, for the Java version, a different new version of Gradle is required to officially support it, but there is no such problem on Maven.

You can see that in my upgraded pom.xml file, only some dependencies have been added, and the compile-time parameters of --add-exports and --add-opens are configured, which cannot be ignored in Gradle. But relatively speaking, just such a little configuration can make the entire project and the sample project run, so there is nothing special. 

Therefore, Gradle must be used to make people difficult to understand, and its configuration file looks very troublesome.

Finally, you can continue to solve the problems caused by Gradle, but this PR may bring some inspiration to others, so that ControlsFx has not been able to upgrade to the latest version of JavaFX. If you use Maven, you can upgrade at any time, even the latest EA version.

**Comment by Zackozz** [comment]
Hey , im new here ! 
i never used Controlfx and things like that. im using Eclipse IDE   and Scene builder 17.
And i want to use Controlfx for the SearchComboBox but i dont know how to install it , i tried in eclipse File import Gradle then put the directory file of Controlfx but it didnt work 
Capture
can someone explain me how to install it with an easy way ? thank you !

**Comment by Yuanuo** [comment]
@Zackozz 
Building controlsfx with Gradle may encounter various errors and fail. So this PR is transformed into a maven build, and even with the latest java18 (EA) and javafx18 (EA) there is no error.

**Comment by g-80** [comment]
@Yuanuo 
Sorry I am a beginner in Java and probably there are a lot like me trying to make this work. Can you tell me how to build your pull request using maven?
I cloned your fork repo and tried to build from `./controlsfx` using `mvn package` but I get an error:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project
 controlsfx: Fatal error compiling: error: release version 18 not supported`

**Comment by Yuanuo** [comment]
Hi.

This error message may be related to the JDK version and Maven version you are using. What versions are you using?

If you are not using the JDK18 version, you can roll back to the previous version of the last Commit, which was still the JDK17 version.

"The previous version refers to" https://github.com/Yuanuo/controlsfx/commit/2aa842d57ac41511aad217e891e6f59f5ac47bd8
[https://opengraph.githubassets.com/f20816119ad8d0e808fef16e1fc78318e92058837b51e6b886ab447a5ba096b7/Yuanuo/controlsfx/commit/2aa842d57ac41511aad217e891e6f59f5ac47bd8]<https://github.com/Yuanuo/controlsfx/commit/2aa842d57ac41511aad217e891e6f59f5ac47bd8>
Added --add-opens declarations for runtime. · ***@***.***<https://github.com/Yuanuo/controlsfx/commit/2aa842d57ac41511aad217e891e6f59f5ac47bd8>
High quality UI controls to complement the core JavaFX distribution - Added --add-opens declarations for runtime. · ***@***.***
github.com

________________________________

**Comment by g-80** [comment]
@Yuanuo 
Thank you. It was my mistake I thought JDK18 version would automatically support JDK17 which is my version.
I did revert the last commit and it worked.

**Comment by abhinayagarwal** [comment]
Thank you for the PR. We will continue using Gradle for now.

**Pull request closed without merging**
