### PR TITLE
Enable headless testing

### PR DESCRIPTION
**Pull request by abhinayagarwal**
We recently enabled tests on 9.0.0 branch. This PR takes us a step forward and enables headless testing using `openjfx-monocle` from TestFX.

### CODE REVIEW

**Comment by Maxoudela** [comment]
I have a weird exception when trying to build:
```
Task :controlsfx:testClasses UP-TO-DATE
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:62300'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:268)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.esotericsoftware.kryo.KryoException: java.io.IOException: Une connexion existante a d� �tre ferm�e par l�h�te distant
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:148)
Caused by: com.esotericsoftware.kryo.KryoException: java.io.IOException: Une connexion existante a d� �tre ferm�e par l�h�te distant

	at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	at com.esotericsoftware.kryo.io.Input.readByte(Input.java:295)
	at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readByte(KryoBackedDecoder.java:81)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:64)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	... 7 more
Caused by: java.io.IOException: Une connexion existante a d� �tre ferm�e par l�h�te distant
```


Which gradle version are you using exactly?

**Comment by abhinayagarwal** [comment]
I have ran `./gradlew test` on ControlsFX with both the current Gradle version: [6.0.1](https://github.com/controlsfx/controlsfx/blob/9.0.0/gradle/wrapper/gradle-wrapper.properties#L6) on 9.0.0 branch and the latest release version 6.3. Both of them seem to work fine.

**Comment by Maxoudela** [comment]
Well I can't make it work on my side but that must comes from my config somehow

**Comment by abhinayagarwal** [comment]
From the exception it seems like you are not running FXSampler 🤔

**Comment by Maxoudela** [comment]
Yes indeed I'm just trying to launch the task Task `:controlsfx:testClasse` . We can merge this anyway, the problem is on my side

**Comment by abhinayagarwal** [comment]
I will refrain from merging this PR until we fix #1258

**Comment by abhinayagarwal** [comment]
Hi @Maxoudela,

I can reproduce the error on my Windows machine. This seems to be related to [JDK-8201539](https://bugs.openjdk.java.net/browse/JDK-8201539).

Please make the following changes to the controlsfx `build.gradle` to test this PR:

1. Update OpenJFX monocle to `12.0.1+2`: 

```
testRuntime ('org.testfx:openjfx-monocle:jdk-12.0.1+2')
```

2. Update JavaFX version to 13:

```
javafx {
    version = "13"
    modules = [ 'javafx.controls', 'javafx.media' ]
}
```

**Comment by Maxoudela** [comment]
I have temporarily lost access to my remote computer, I'll test all that on monday! Thanks for the research and tips!

**Comment by Maxoudela** [comment]
Allright, the headless tests are working with the given configuration!

**Pull request merged**
