### PR TITLE
fix contentY computation for ToggleSwitch when thumb and thumb-area have different height

### LINKED ISSUE #1343: ToggleSwitch: Thumb bigger than thumb-area results in layout misalignment
Given the simple example below the ToggleSwitch does not correctly layout when its look is changed through CSS. This is the result:
grafik
The code:
```
public class ToggleBug extends Application {
    public static void main(String[] args) {
        launch(args);
    }
    
    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Hello World!");
        HBox box = new HBox();
        Button btn = new Button();
        btn.setText("Say 'Hello World'");
        btn.setMinHeight(50);
        ToggleSwitch toggle = new ToggleSwitch();
        toggle.getStylesheets().add(getClass().getResource("toggle.css").toExternalForm());
        box.getChildren().addAll(btn, toggle);
        primaryStage.setScene(new Scene(box, 300, 250));
        primaryStage.show();
    }
}
```
The toggle.css file:
```
.toggle-switch .thumb {
	-fx-background-radius: 17;
	-fx-padding: 17;
}

.toggle-switch .thumb-area{
    -fx-background-radius: 5;
    -fx-padding: 5 50 5 50; /* describes length: 50+50 = 100 width, 5+5=10 height */
}
```
ControlsFX version: 8.40.18
OpenJDK 1.8.0_232

**The problem:**
The skin/layouting always assumes that the thumb and thumb-area have the same height when in this case the thumb is bigger. So I wrote a hack/fix to workaround this problem:

```
public class ToggleSwitchVCentered extends ToggleSwitch
{
  @Override
  protected Skin createDefaultSkin()
  {
    return new Skin(ToggleSwitchVCentered.this);
  }

  class Skin extends ToggleSwitchSkin
  {
    private Node thumbArea;
    private double height;

    private Node getThumbArea()
    {
      if (thumbArea == null)
      {
        String styleClass = "thumb-area";
        thumbArea = getChildren()
            .stream()
            .filter(n -> n.getStyleClass()
                .stream()
                .anyMatch(styleClass::equals))
            .findAny()
            .orElseThrow(NoSuchElementException::new);
      }
      return thumbArea;
    }


    public Skin(ToggleSwitch control)
    {
      super(control);
    }

    @Override
    protected double snapPosition(double contentY)
    {
      if(height > 0)
        contentY += (height / 2) - (getThumbArea().prefHeight(-1) / 2);
      return super.snapPosition(contentY);
    }

    @Override
    protected void layoutChildren(double contentX, double contentY, double contentWidth, double contentHeight)
    {
      height = contentHeight;
      super.layoutChildren(contentX, contentY, contentWidth, contentHeight);
      height = -1;
    }
  }
}
```

The first call of _snapPosition_ in _layoutChildren_ sets the _thumbAreaY_ which is the base for the vertical layouting. With this workaround both the thumb and the thumb-area height are taken into account.

### PR DESCRIPTION
**Pull request by chilliger**
Fixes #1343

### CODE REVIEW

**Comment by Maxoudela** [comment]
Could you target "jfx-13" branch which is our default one now? I'll take a look asap next week. Thanks

**Comment by chilliger** [comment]
I hope it gets merged into the master branch because we use java 8

**Comment by abhinayagarwal** [comment]
Hi @chilliger ,

ControlsFX won't be released for Java 8 any more. All our development and bug fix efforts are towards JDK 11 and later.

**Comment by Maxoudela** [comment]
Seems good, could you update the Copyright of the files modified?

**Review by Maxoudela — APPROVED** [review]

**Comment by abhinayagarwal** [comment]
I am not sure if we want to merge this. `master` branch will be removed once #1345 is implemented.

**Comment by abhinayagarwal** [comment]
Closing as the PR targeted for `jfx-13` has been merged.

**Pull request closed without merging**
