### PR TITLE
#1384: Fix using active popups as owners for new popups

### LINKED ISSUE #1384: Some notifications disappearing too early when application has no active window
Without any active application window and multiple notifications showing, all will disappear at the same time as the oldest one. This happens because active notifications are taken an owner for new notifications. When owner disappears - child popups also disappear. Popup owner is set here:
https://github.com/controlsfx/controlsfx/blob/jfx-13/controlsfx/src/main/java/org/controlsfx/control/Notifications.java#L501
`ownerWindow` value from here:
https://github.com/controlsfx/controlsfx/blob/jfx-13/controlsfx/src/main/java/org/controlsfx/control/Notifications.java#L378-L385
could be used instead to avoid the issue.

### PR DESCRIPTION
**Pull request by dawidm**
fixes #1384

### CODE REVIEW

**Review by Maxoudela — APPROVED** [review]

**Comment by Maxoudela** [comment]
Can you sign the CLA @dawidm ?

**Comment by dawidm** [comment]
> Can you sign the CLA @dawidm ?

Yes, I just did it.

**Comment by abhinayagarwal** [comment]
Hi @dawidm ,

Is it possible to test this change via a Test?

**Comment by dawidm** [comment]
> Hi @dawidm ,
> 
> Is it possible to test this change via a Junit Test?

Hi, I don't think so.

**Comment by abhinayagarwal** [comment]
OK, I will merge the PR as @Maxoudela has already approved it.

**Pull request merged**
