### PR TITLE
Fix VirtualFlow access in GridViewSkin

### LINKED ISSUE #1330: GridViewSkin should no longer use reflection to access VirtualFlow
Since JDK 10, `VirtualContainerBase#getVirtualFlow()` is available to be used by GridViewSkin. We should replace the reflection usage and use this instead.

### PR DESCRIPTION
**Pull request by abhinayagarwal**
Fixes #1330

### CODE REVIEW

**Review by Maxoudela — APPROVED** [review]

**Comment by Hugolarson** [comment]
Hi.
Downloaded and build controlsFx but this issue is still there.
If merged should this fix not be included?

**Comment by abhinayagarwal** [comment]
Hi @Hugolarson ,

Can you please post the error in https://github.com/controlsfx/controlsfx/issues/1330 ?

**Comment by Hugolarson** [comment]
20-12-01 10:10:32| [JavaFX Application Thread|]:advit.log.LoggerHelper uncaughtException JavaFX Application Thread 
java.lang.reflect.InaccessibleObjectException: Unable to make protected void javafx.scene.control.skin.VirtualFlow.reconfigureCells() accessible: module javafx.controls does not "opens javafx.scene.control.skin" to unnamed module @67cf97e0
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	at impl.org.controlsfx.ReflectionUtils.reconfigureCells(ReflectionUtils.java:117)
	at impl.org.controlsfx.skin.GridViewSkin.updateItemCount(GridViewSkin.java:133)
	at impl.org.controlsfx.skin.GridViewSkin.updateGridViewItems(GridViewSkin.java:95)
	at impl.org.controlsfx.skin.GridViewSkin.<init>(GridViewSkin.java:53)
	at org.controlsfx.control.GridView.createDefaultSkin(GridView.java:142)

**Comment by abhinayagarwal** [comment]
This is different from the earlier issue. This particular issue is caused because `GridViewSkin` needs to access `VirtualFlow#rebuildCells` and `VirtualFlow#reconfigureCells`, which are protected methods and not accessible to `GridViewSkin`.

@Maxoudela Do you have a suggestion on how to fix this?

**Comment by Maxoudela** [comment]
We should dig a bit on the GridViewSkin to see if those two calls are still necessary for the GridView to work. The code is a bit old so maybe it's not useful anymore.

If it's still useful, I suggest doing like I do on the spreadsheet.GridViewSkin. Override the `createVirtualFlow()` method in order to provide a custom VirtualFlow that would either open these two methods, or help accessing them.

**Comment by Hugolarson** [comment]
Need to ask what the status is of this issue with GridViewSkin https://github.com/controlsfx/controlsfx/pull/1331#issuecomment-736246489

**Comment by abhinayagarwal** [comment]
@Hugolarson There hasn't been any work done on it. I have logged #1332 for a follow up. If you would like to work on it please go ahead.

**Pull request merged**
