### PR TITLE
Wrap long exception message

### LINKED ISSUE #1211: Wrap content in exception dialog
Without preferred width the content label will not wrap, only expand the dialog.

#1155 is incomplete see also DialogPane#createContentLabel(String)

Simple test:

    public static void main(String[] args) {
        new JFXPanel();

        Platform.runLater(() -> {
            Exception e = new IllegalStateException("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.");
            ExceptionDialog dialog = new ExceptionDialog(e);
            dialog.showAndWait();
        });
    }

### PR DESCRIPTION
**Pull request by falkoschumann**
Extra: simplify code and use localised exception message

Fixes #1211

### CODE REVIEW

**Comment by Maxoudela** [comment]
Thanks for the PR, have you signed the [CLA](https://docs.google.com/forms/d/e/1FAIpQLSfGmJDMdl9mPBiZLwhUXPNRKcSSJDawBHe_ED2ReSJGUt-puQ/viewform) as mentioned in the [Contributing doc](https://github.com/controlsfx/controlsfx/wiki/Contributing-to-ControlsFX)?

**Comment by falkoschumann** [comment]
Copyright updated and CLA signed.

**Comment by abhinayagarwal** [comment]
@Maxoudela Indeed. May be something Jonathan missed while creating the control.

@falkoschumann  This PR looks good. Would you mind adding a small description of the control to its Javadoc?

**Comment by Maxoudela** [comment]
All specific dialogs do not have javadoc, I'll create an issue for that so that we can merge this one.

**Pull request merged**
