### PR TITLE
fix for bitbucket #748

### PR DESCRIPTION
**Pull request by FlorianKirmaier**
fixing https://bitbucket.org/controlsfx/controlsfx/issues/748/memory-leak-in-actionutils-permanent

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
Can we target this PR to `master`?

**Comment by FlorianKirmaier** [comment]
master is basically the java8-branch and it "regulary" gets merged back to 11?
Ok, I will make a new pullrequest based on the other version.
After looking further into the code, I noticed there are some more cornercases which must be fixed. I will update my changes and probably add some unit-tests for it.

**Comment by abhinayagarwal** [comment]
Yes, that's right. Changes from `master` is always merged back to the `9.0.0` branch.

**Comment by FlorianKirmaier** [comment]
Closing in favor of the new PR based on the master branch:
https://github.com/controlsfx/controlsfx/pull/1202

**Pull request closed without merging**
